# Generated by Django 4.1.3 on 2024-01-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('key_skills', models.CharField(max_length=256, verbose_name='Навыки')),
                ('salary_from', models.DecimalField(decimal_places=1, max_digits=16, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(decimal_places=1, max_digits=16, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(max_length=4, verbose_name='Валюта')),
                ('area_name', models.CharField(max_length=128, verbose_name='Город')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
