# Generated by Django 4.1.3 on 2024-01-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0002_vacancy_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
