# Generated by Django 4.1.3 on 2024-01-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0003_alter_vacancy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('date', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Дата')),
                ('USD', models.CharField(max_length=3, null=True, verbose_name='USD')),
                ('BYR', models.CharField(max_length=3, null=True, verbose_name='BYR')),
                ('EUR', models.CharField(max_length=3, null=True, verbose_name='EUR')),
                ('KZT', models.CharField(max_length=3, null=True, verbose_name='KZT')),
                ('UAH', models.CharField(max_length=3, null=True, verbose_name='UAH')),
                ('AZN', models.CharField(max_length=3, null=True, verbose_name='AZN')),
                ('KGS', models.CharField(max_length=3, null=True, verbose_name='KGS')),
                ('UZS', models.CharField(max_length=3, null=True, verbose_name='UZS')),
                ('GEL', models.CharField(max_length=3, null=True, verbose_name='GEL')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=1, max_digits=16, null=True, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
    ]
