# Generated by Django 4.1.3 on 2024-01-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0004_currency_vacancy_date_vacancy_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('area_name', models.CharField(max_length=128, verbose_name='Город')),
                ('salary', models.DecimalField(decimal_places=1, max_digits=16, null=True, verbose_name='Зарплата')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Форматированная вакансия',
                'verbose_name_plural': 'Форматированные вакансии',
            },
        ),
    ]
