# Generated by Django 4.1.3 on 2024-01-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0005_formedvacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formedvacancy',
            name='date',
            field=models.CharField(max_length=10, null=True, verbose_name='Дата публикации'),
        ),
    ]
