# Generated by Django 4.1.3 on 2024-01-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0006_alter_formedvacancy_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_avg', models.DecimalField(decimal_places=1, max_digits=16, verbose_name='Средняя з/п')),
                ('vacancies_amount', models.IntegerField(verbose_name='Количество вакансий')),
                ('salary_avg_prof', models.DecimalField(decimal_places=1, max_digits=16, verbose_name='Средняя з/п C#')),
                ('vacancies_amount_prof', models.IntegerField(verbose_name='Количество вакансий C#')),
            ],
            options={
                'verbose_name': 'Годовая статистика',
                'verbose_name_plural': 'Статистика по годам',
            },
        ),
    ]
