# Generated by Django 4.1.3 on 2024-01-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0008_remove_statbyyear_id_statbyyear_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatByArea',
            fields=[
                ('area', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Город')),
                ('salary_avg', models.DecimalField(decimal_places=1, max_digits=16, null=True, verbose_name='Средняя з/п ')),
                ('vacancies_percent', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Доля вакансий')),
                ('salary_avg_prof', models.DecimalField(decimal_places=1, max_digits=16, null=True, verbose_name='Средняя з/п С#')),
                ('vacancies_percent_prof', models.DecimalField(decimal_places=1, max_digits=16, null=True, verbose_name='Доля вакансий С#')),
            ],
        ),
    ]
