# Generated by Django 4.1.3 on 2024-01-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0009_statbyarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statbyarea',
            old_name='area',
            new_name='area_name',
        ),
    ]
