# Generated by Django 4.1.3 on 2024-01-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0010_rename_area_statbyarea_area_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
