# Generated by Django 4.1.3 on 2024-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0011_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAvgAreaProfTop10',
            fields=[
                ('area_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Город')),
                ('salary_avg', models.DecimalField(decimal_places=1, max_digits=16, verbose_name='Средняя з/п ')),
            ],
            options={
                'verbose_name': 'Статистика по городу по профессии c#',
                'verbose_name_plural': 'Статистика по лучшим городам по профессии c#',
            },
        ),
        migrations.CreateModel(
            name='SalaryAvgAreaTop10',
            fields=[
                ('area_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Город')),
                ('salary_avg', models.DecimalField(decimal_places=1, max_digits=16, verbose_name='Средняя з/п ')),
            ],
            options={
                'verbose_name': 'Статистика по городу',
                'verbose_name_plural': 'Статистика по лучшим городам',
            },
        ),
        migrations.CreateModel(
            name='VacanciesPercentAreaProfTop10',
            fields=[
                ('area_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Город')),
                ('vacancies_percent', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Доля вакансий в городе по профессии c#',
                'verbose_name_plural': 'Доли вакансий в городах по профессии c#',
            },
        ),
        migrations.CreateModel(
            name='VacanciesPercentAreaTop10',
            fields=[
                ('area_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Город')),
                ('vacancies_percent', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Доля вакансий в городе',
                'verbose_name_plural': 'Доли вакансий в городах',
            },
        ),
        migrations.AlterModelOptions(
            name='statbyarea',
            options={'verbose_name': 'Статистика по городу', 'verbose_name_plural': 'Статистика по городам'},
        ),
    ]
