# Generated by Django 4.1.3 on 2024-01-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_stat', '0013_rename_salary_avg_salaryavgareaproftop10_salary_avg_prof_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryavgareaproftop10',
            options={'verbose_name': 'Статистика по городу для профессии c#', 'verbose_name_plural': 'Статистика по лучшим городам для профессии c#'},
        ),
        migrations.AlterModelOptions(
            name='vacanciespercentareaproftop10',
            options={'verbose_name': 'Доля вакансий в городе для профессии c#', 'verbose_name_plural': 'Доли вакансий в городах для профессии c#'},
        ),
    ]
